### ISSUE TITLE
Hamburger in navbar for mobile view

### ISSUE THREAD

**Issue by mohit355** [GDSC-IIIT-Kalyani/placement-portal#11]
Add a hamburger for a navbar
![image](https://user-images.githubusercontent.com/54148372/132483572-eb3a76a9-f281-46ba-95d1-b9dc787082cc.png)

Comment down your name below, if you want to work on this issue

**Comment by jatinverma14** [comment]
sir, can i work on this issue?

**Comment by mohit355** [comment]
@jatinverma14  go ahead
