### ISSUE TITLE
Decrease font-size of college name heading.

### ISSUE THREAD

**Issue by mohit355** [GDSC-IIIT-Kalyani/placement-portal#15]
Try to adjust it in max 2 line, in mobile view
![image](https://user-images.githubusercontent.com/54148372/135796296-f79b5dc6-662c-47d7-942d-c75bb130480e.png)

**Comment by unnati-bhatia** [comment]
I want to try and fix this issue.

**Comment by mohit355** [comment]
@unnati-bhatia  go ahead

**Comment by AnuragParashar2000** [comment]
hey I want to work on this issue

**Comment by AnuragParashar2000** [comment]
@mohit355

**Comment by mohit355** [comment]
> hey I want to work on this issue

@AnuragParashar2000  This issue is already assigned.

**Comment by AnuragParashar2000** [comment]
ok

**Comment by vishalram14** [comment]
Could you check I have solved this issue

**Comment by vishalram14** [comment]
Hey, Sorry I was didn't see this space, kindly ignore my pull request if it is not valid
