### ISSUE TITLE
Remove canteen and hospital image from Infrastructure section

### ISSUE THREAD

**Issue by mohit355** [GDSC-IIIT-Kalyani/placement-portal#16]
Remove Hospital and Canteen section from Infrastructure section.
After removing, it must be responsive.

![image](https://user-images.githubusercontent.com/54148372/135798980-f9681929-8895-4975-bcbd-1aa742a5c72c.png)

**Comment by rajmunkhan** [comment]
@mohit355 I will work on this, plz assign it to me

**Comment by mohit355** [comment]
@rajmunkhan  go ahead

**Comment by rajmunkhan** [comment]
@mohit355 I have changed everything accordingly, check the pr #27 and let me know.
