### ISSUE TITLE
Remove Mentor Institute link for Quick Links of Footer

### ISSUE THREAD

**Issue by mohit355** [GDSC-IIIT-Kalyani/placement-portal#17]
Remove the link marked in red in below image
![image](https://user-images.githubusercontent.com/54148372/135799185-6cece41c-182b-4fb1-b77b-ab73003162a7.png)

**Comment by JanviRaina** [comment]
Will do this.

**Comment by vishalram14** [comment]
Can I work on this or has it been solved
