### ISSUE TITLE
Add Links in the Footer sections

### ISSUE THREAD

**Issue by mohit355** [GDSC-IIIT-Kalyani/placement-portal#18]
Add links to all the red marked sections. You need to research to get the links.
Reference : http://iiitkalyani.ac.in/
![image](https://user-images.githubusercontent.com/54148372/135799433-b03d3266-b056-4385-995c-a7acc5eb0422.png)

**Comment by matrixbot123** [comment]
I can do this.

**Comment by Ayush0922** [comment]
i can do this , can you please assign me.

**Comment by Prayag-X** [comment]
i can do this too

**Comment by mohit355** [comment]
Since it's a first come first serve basis @matrixbot123  will work on this issue. if he/she is not able to complete a PR within the next 2 days then this issue will be transferred to the next person.

I am creating more issues, keep your eye on the issues section.

**Comment by mohit355** [comment]
@matrixbot123  go ahead

**Comment by matrixbot123** [comment]
> @matrixbot123 go ahead

okay,Thanks !
