### ISSUE TITLE
Section's heading's text overflow

### ISSUE THREAD

**Issue by jatinverma14** [GDSC-IIIT-Kalyani/placement-portal#22]
"Students Performance" heading is out of the box. Its font size has to be decreased.
![2021-10-04 (2)](https://user-images.githubusercontent.com/75436955/135802572-020c629d-845a-47b9-89b0-d180fb4713d7.png)

**Comment by jatinverma14** [comment]
Sir, can I work on this?

**Comment by mohit355** [comment]
@jatinverma14  go ahead and fix it. fix all the text that is overflowing
