### ISSUE TITLE
Align text left of paragraph  'Why Recruit at IIIT Kalyani? ' Section 

### ISSUE THREAD

**Issue by mohit355** [GDSC-IIIT-Kalyani/placement-portal#30]
Make text alignment left (excluding the headings)
![image](https://user-images.githubusercontent.com/54148372/135891871-97b50513-30b4-484e-8f9b-1d102f9dc759.png)

**Comment by pavankalyan-codes** [comment]
Hey! can you assign this to me

**Comment by mohit355** [comment]
@pavankalyan-codes  go ahead
