### ISSUE TITLE
Redesign hover effect of placement stats button

### ISSUE THREAD

**Issue by mohit355** [GDSC-IIIT-Kalyani/placement-portal#31]
The below image showing a button without a hover effect
![image](https://user-images.githubusercontent.com/54148372/135892408-62db6af5-ab29-411d-a041-3868200c0971.png)

The below image showing a button with a hover effect
![image](https://user-images.githubusercontent.com/54148372/135892569-0b7517a0-51b8-4d1c-91c8-ac780caf1d67.png)

change the background color to black and text color to white on hover effect

**Comment by unnati-bhatia** [comment]
May I try sir.

**Comment by mohit355** [comment]
@unnati-bhatia  go ahead

**Comment by GauravSingh9356** [comment]
can I try it @mohit355 sir

**Comment by unnati-bhatia** [comment]
Sir, I have completed this issue but cannot make 2 PR simultaneously. So, when I get previous one accepted then I will request for this too.
