### ISSUE TITLE
Bring PLACEMENT STATISTICS text at top

### ISSUE THREAD

**Issue by mohit355** [GDSC-IIIT-Kalyani/placement-portal#35]
![image](https://user-images.githubusercontent.com/54148372/135893739-af73d6ff-8a94-4470-ae1f-52aa72c23574.png)

**Comment by ShashankJais128** [comment]
Hey! can I work on this?

**Comment by ShashankJais128** [comment]
hi! why this repo is showing as "excluded project" in hacktoberfest

**Comment by pavankalyan-codes** [comment]
Hey I can work on this. Pls assign this to me

**Comment by mohit355** [comment]
@ShashankJais128  go ahead. make a PR under 2 days otherwise, this will get assigned to @pavankalyan-codes

**Comment by ShashankJais128** [comment]
Ok.

**Comment by ShashankJais128** [comment]
the only thing we have to do here is to shift the "placement statistics" row to the top, right?
