### ISSUE TITLE
Improve the hover effect in the Brochure Button

### ISSUE THREAD

**Issue by harshalw07** [GDSC-IIIT-Kalyani/placement-portal#46]
need to improve the button hover styles

**Comment by ankeeta-ahire** [comment]
Please assign me this issue.

**Comment by anuj2801** [comment]
Sir i can do this

**Comment by mohit355** [comment]
@harshalw07  go ahead and make a PR under 2 days

**Comment by ankeeta-ahire** [comment]
@mohit355 I have completed the task and done with PR. Kindly check it.

**Comment by ankeeta-ahire** [comment]
@mohit355 please check it.
