### ISSUE TITLE
Adding links to twitter, Youtube and mail to icons in contact us section

### ISSUE THREAD

**Issue by anuj2801** [GDSC-IIIT-Kalyani/placement-portal#51]
![vrw](https://user-images.githubusercontent.com/81874270/136235679-e25e7dc9-efa9-4917-8d2b-189697f12824.jpg)

**Comment by dubeyadarsh** [comment]
Can u assign me this ?... I would like to contribute to this project !! Kindly assign me !

**Comment by mohit355** [comment]
@anuj2801  go ahead. make a PR within 2 days, otherwise it will assigned to @dubeyadarsh
